core:
  - changed-files:
      - any-glob-to-any-file:
          - src/client.zig
          - src/gateway/**
          - src/rest/**
models:
  - changed-files:
      - any-glob-to-any-file:
          - src/models/**
cache:
  - changed-files:
      - any-glob-to-any-file:
          - src/cache/**
ext:
  - changed-files:
      - any-glob-to-any-file:
          - src/ext/**
ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
docs:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - CONTRIBUTING.md
          - CODE_OF_CONDUCT.md
