name: CI
on:
  pull_request:
  push:
    branches: [main, develop]
permissions:
  contents: read
jobs:
  build-test:
    name: build & test (${{ matrix.os }}, Zig ${{ matrix.zig }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        zig: ["0.13.0"]
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with: { version: ${{ matrix.zig }} }
      - name: Format (check)
        run: zig fmt --check .
      - name: Build
        run: zig build
      - name: Tests
        run: zig build test
