name: Commit & PR title policy

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install commitlint (pinned)
        run: |
          npm i -g @commitlint/cli@18 @commitlint/config-conventional@18

      - name: Validate commits
        env:
          BASE: ${{ github.event.pull_request.base.sha }}
          HEAD: ${{ github.event.pull_request.head.sha }}
        run: |
          npx commitlint --from="$BASE" --to="$HEAD"

      - name: Validate PR title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          SAFE_TITLE="$(printf '%s' "$TITLE" | tr -cd '[:alnum:] .:_-')"
          printf '%s\n' "$SAFE_TITLE" | npx commitlint
