name: PR Size
on:
  pull_request:
permissions: { pull-requests: write, contents: read }
jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/size-label-action@v0.5.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORED: "yarn.lock package-lock.json zig-cache zig-out"
          SIZES: >
            {
              "XS": 10,
              "S": 100,
              "M": 500,
              "L": 1000,
              "XL": 2000
            }
