name: PR Size

on:
  pull_request:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write
  issues: write

concurrency:
  group: pr-size-${{ github.event.pull_request.node_id || github.run_id }}
  cancel-in-progress: true

jobs:
  size:
    runs-on: ubuntu-latest
    if: >
      ${{
        github.event_name == 'pull_request_target' ||
        (github.event_name == 'pull_request' &&
         github.event.pull_request.head.repo.full_name == github.repository)
      }}
    steps:
      - uses: pascalgn/size-label-action@v0.5.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORED: "yarn.lock package-lock.json zig-cache zig-out"
          SIZES: >
            { "XS": 10, "S": 100, "M": 500, "L": 1000, "XL": 2000 }
